### PR TITLE
Lexi Version 3

### PR DESCRIPTION
**Pull request by thetayloredman**
This pull request contains the rapid-iteration progress on Lexi 3.

To-do:

- [x] Rebrand to Lexi
- [x] Use Yarn instead of NPM
- [x] PNP (plug n play) modules?
- [x] https://github.com/thetayloredman/ProtoBot/pull/511 suggested by @RealShadowNova
- [x] https://github.com/thetayloredman/ProtoBot/issues/519: **stopped:** needs consideration
- [x] Upgrade to Chalk 5 again -- **superseded by https://github.com/thetayloredman/ProtoBot/pull/511 -- chalk is no longer used**
- [x] Publish CI system (lexi-upgrader) -- **ruled against:** no its mine for now
- [x] Repo renaming
  - [x] Rename the actual gh.
  - [x] Change remotes for all devs.
  - [x] Change remotes on prod server.
  - [x] Update lexidup
- [x] Rename CI systems
- [x] [JOSH](https://josh.evie.dev/) -- **cancelled:** Wait for JOSH 2
- [x] Module renames
- [x] Legacy code audit
- [x] Logging changes
- [x] https://github.com/thetayloredman/ProtoBot/issues/436
  - [x] Needed modules to be installed
  - [x] Rewrite command handler
  - [x] Permissions system
  - [x] Rewrite hooks system
  - [x] Migrate existing commands
  - [x] Remove old outdated legacy code
    - [x] Legacy CMDs
    - [x] Legacy functions
- [x] README changes
- [x] General operations
  - [x] Rename bot apps
  - [x] Rename bot accounts

### CODE REVIEW

**Comment by RealShadowNova** [comment]
Your supposed to use the named exports from colorette

**Comment by thetayloredman** [comment]
@RealShadowNova and what is "supposed"?

**Comment by RealShadowNova** [comment]
> @RealShadowNova and what is "supposed"?

Most modern projects use named exports and it is much cleaner code generally.

**Comment by thetayloredman** [comment]
So you're saying to do stuff like:

```js
import { red, bold, underline } from 'colorette';
```

instead of `* as colorette from 'colorette'`?

**Comment by thetayloredman** [comment]
To-do: finish #519

**Comment by thetayloredman** [comment]
Alright... time to really go for slash.

**Review by ilikestohack — APPROVED** [review]

**Pull request merged**
