### PR TITLE
refactor: no more @discordjs/rest

### LINKED ISSUE #571: use application.commands.set instead of @djs/rest

### PR DESCRIPTION
**Pull request by thetayloredman**
**Does this Pull Request fix an issue? If so, please mention the issue.**
Closes #571

**Describe your changes.**
Use applications.commands.set.

### CODE REVIEW

**Comment by thetayloredman** [comment]
Supersedes #565.

**Review by ilikestohack — APPROVED** [review]
Looks good

**Review by ilikestohack — APPROVED** [review]
Still looks good

**Comment by thetayloredman** [comment]
Final tests passed. Merge.

**Pull request merged**
